/**
 * 文件名或扩展名到 SVG 图标的映射表。
 * 键 (key): 文件名 (如 'package.json') 或文件扩展名 (如 '.ts')
 * 值 (value): 对应的 SVG 图标文件名 (如 'typescript.svg')
 */
export const fileIconMap: { [key: string]: string } = {
  // 常用语言/文件类型
  ".ts": "typescript.svg",
  ".js": "javascript.svg",
  ".mjs": "javascript.svg",
  ".cjs": "javascript.svg",
  ".tsx": "react_ts.svg",
  ".jsx": "react.svg",
  ".html": "html.svg",
  ".htm": "html.svg",
  ".css": "css.svg",
  ".scss": "sass.svg",
  ".sass": "sass.svg",
  ".less": "less.svg",
  ".json": "json.svg",
  ".yaml": "yaml.svg",
  ".yml": "yaml.svg",
  ".md": "markdown.svg",
  ".markdown": "markdown.svg",
  ".py": "python.svg",
  ".java": "java.svg",
  ".jar": "jar.svg",
  ".c": "c.svg",
  ".h": "h.svg",
  ".cpp": "cpp.svg",
  ".hpp": "hpp.svg",
  ".cs": "csharp.svg",
  ".go": "go.svg",
  ".rs": "rust.svg",
  ".swift": "swift.svg",
  ".php": "php.svg",
  ".rb": "ruby.svg",
  ".dart": "dart.svg",
  ".vue": "vue.svg",
  ".svelte": "svelte.svg",
  ".sh": "bashly.svg",
  ".sql": "database.svg",
  ".xml": "xml.svg",
  ".svg": "svg.svg",
  ".png": "image.svg",
  ".jpg": "image.svg",
  ".jpeg": "image.svg",
  ".gif": "image.svg",
  ".mp3": "audio.svg",
  ".wav": "audio.svg",
  ".mp4": "video.svg",
  ".mov": "video.svg",
  ".pdf": "pdf.svg",
  ".zip": "zip.svg",
  ".exe": "exe.svg",

  // 配置/工具文件
  "package.json": "npm.svg",
  "go.mod": "go-mod.svg",
  gemfile: "gemfile.svg",
  dockerfile: "docker.svg",
  "docker-compose.yml": "docker.svg",
  "tsconfig.json": "tsconfig.svg",
  "jsconfig.json": "jsconfig.svg",
  "babel.config.js": "babel.svg",
  "webpack.config.js": "webpack.svg",
  "tailwind.config.js": "tailwindcss.svg",
  "next.config.js": "next.svg",
  ".gitignore": "git.svg",
  ".gitattributes": "git.svg",
  ".editorconfig": "editorconfig.svg",
  ".eslintrc": "eslint.svg",
  ".stylelintrc": "stylelint.svg",
  ".prettierrc": "prettier.svg",
  ".env": "settings.svg",
  "readme.md": "readme.svg",
  license: "certificate.svg",
  "changelog.md": "changelog.svg",
  browserslist: "browserlist.svg",
  "commitlint.config.js": "commitlint.svg",
  jenkinsfile: "jenkins.svg",
  "netlify.toml": "netlify.svg",
  "vite.config.ts": "vite.svg",
};

/**
 * 文件夹名称到 SVG 图标的映射表（仅列出 closed 状态的图标）。
 * 键 (key): 文件夹名称 (如 'src')
 * 值 (value): 对应的 'closed' 状态 SVG 图标文件名 (如 'folder-src.svg')
 */
export const folderIconMap: { [key: string]: string } = {
  src: "folder-src.svg",
  source: "folder-src.svg",
  app: "folder-app.svg",
  api: "folder-api.svg",
  client: "folder-client.svg",
  server: "folder-server.svg",
  config: "folder-config.svg",
  configs: "folder-config.svg",
  dist: "folder-dist.svg",
  build: "folder-dist.svg",
  out: "folder-dist.svg",
  test: "folder-test.svg",
  tests: "folder-test.svg",
  __tests__: "folder-test.svg",
  e2e: "folder-test.svg",
  spec: "folder-test.svg",
  scripts: "folder-scripts.svg",
  tools: "folder-tools.svg",
  assets: "folder-resource.svg",
  resources: "folder-resource.svg",
  images: "folder-images.svg",
  img: "folder-images.svg",
  icons: "folder-images.svg",
  styles: "folder-css.svg",
  css: "folder-css.svg",
  sass: "folder-sass.svg",
  fonts: "folder-font.svg",
  components: "folder-components.svg",
  widgets: "folder-components.svg",
  views: "folder-views.svg",
  pages: "folder-views.svg",
  routes: "folder-routes.svg",
  public: "folder-public.svg",
  static: "folder-public.svg",
  utils: "folder-utils.svg",
  helpers: "folder-helper.svg",
  lib: "folder-lib.svg",
  libraries: "folder-lib.svg",
  db: "folder-database.svg",
  database: "folder-database.svg",
  migrations: "folder-database.svg",
  data: "folder-database.svg",
  docs: "folder-docs.svg",
  documentation: "folder-docs.svg",
  i18n: "folder-i18n.svg",
  locale: "folder-i18n.svg",
  environments: "folder-environment.svg",
  environment: "folder-environment.svg",
  ".vscode": "folder-vscode.svg",
  ".github": "folder-github.svg",
  ".git": "folder-git.svg",
  node_modules: "folder-node.svg",
  cypress: "folder-cypress.svg",
  next: "folder-next.svg",
  nuxt: "folder-nuxt.svg",
  vue: "folder-vue.svg",
  angular: "folder-angular.svg",
};
